#!/bin/python3
import urllib.request, os.path
from mangaManagement.management import *
os.system("clear")
mangaListList=[]
scanPath = "/media/mawena/Files/Files/Documents/Divertissements/scan/"
mangaListList = getMangaListListLocal("/media/mawena/Files/Files/Documents/Divertissements/scan/", "jpg")

if(len(mangaListList) > 0):
    mangaNumList = getMangaNumList(mangaListList)
    #3-Compréssion des images:
    for mangaNum in mangaNumList:    #Boucle de compréssion des images
        mangaNum = int(mangaNum)-1
        name,imagePath,cbzName = mangaListList[mangaNum]    #Definition des variables après lecture des informations
        cbzPath = "{0}{1}/cbz/".format(scanPath, name)
        chapitreList, temp=os.listdir(imagePath), cbzName
        for chapitre in chapitreList:
            if (containsListWords(chapitre.upper(), ["TOME"])):    #Si le name dossier est un tome
                cbzName=""
            else:
                cbzName = temp
            os.system("clear")
            if os.path.exists(cbzPath) == False:
                os.makedirs(cbzPath)  #On crée le dossier de destination du cbz
                print("Etape2: Compréssions:\nCréation du dossier"+cbzPath)
            print("Chapitre {0}".format(chapitre))
            os.system("zip -r9j '"+cbzPath+cbzName+chapitre+".cbz' '"+imagePath+chapitre+"/'*")
    rmMangasImages(mangaListList, mangaNumList)
else:
    print("Il n'y a aucun manga à convertir")
#BYMawena