#!/bin/python3
import os
import sys
paths=[]
if len(sys.argv) > 1:	#Si on a un ou plusieurs paramètres
	i = 1
	while i < len(sys.argv):
		paths.append(os.path.abspath(sys.argv[i]))	#On les convertit en chemin absolu
		i+=1
else:	#Sinon le chemin par défaut est le dossier courant
	paths = [os.getcwd()]

Types=["Vidéo","Chapter"]
Type = Types[int(input("Vidéo(0) ou Chapitre(1)?:"))]
nbPartie = int(input("Nombre de partie[int]:"))
nbTxt = int(input("Nombre de fichier txt par partie[int]:"))

for path in paths:
	for i in range(1, nbPartie+1):
		nomPartie=input("nom de la partie"+str(i)+":")
		os.system("mkdir "+path+"/Part"+str(i))
		for j in range(1, nbTxt+1):
			os.system("touch "+path+"/Part"+str(i)+"/"+str(j)+"-.txt")
			os.system('echo """Part'+str(i)+': '+nomPartie+'\n'+Type+str(j)+""": 

						/1/-Important notes:
#

						/2/-Supplements and info:
-

										#BY MAWENA
"""+'""" >> '+path+"/Part"+str(i)+"/"+str(j)+"-.txt")