#!/bin/python3
import os, sys, mangaManagement
from mangaManagement.management import *
os.system("clear")
mangaListList=[]
scanPath = "/media/mawena/Files/Files/Documents/Divertissements/scan/"
mangaListList = getMangaListListLocal("/media/mawena/Files/Files/Documents/Divertissements/scan/", "pdf")

if(len(mangaListList)>0):
	mangaNumList = getMangaNumList(mangaListList)
	for mangaNum in mangaNumList:	#Boucle de compréssion des images
		mangaNum = int(mangaNum)-1
		name, imagesPath, prefixe = (mangaListList[mangaNum])
		pdfPath = scanPath+name+"/pdf/"

		for pdfFile in os.listdir(pdfPath):
			if(pdfFile.__contains__(".pdf")):
				pdfNum = (((pdfFile.split(".pdf"))[0]).split(prefixe))[1]
				os.makedirs("{0}/{1}".format(imagesPath, pdfNum), exist_ok=True)
				if (len(os.listdir(imagesPath+pdfNum+"/")) == 0):
					os.system("pdfimages -j {0}{2} {3}{1}/".format(pdfPath, pdfNum, pdfFile, imagesPath))
		rmItems(pdfPath, ".pdf")
else:
	print("Il n'y a pas d'images à convertir")