#!/bin/bash

function _foremost() {
#On crée le formulaire en stockant les valeurs de sortie dans $cfgpass :/
parts=`df -Th | grep -e "^/dev/*" | tr "\n" "|"`
cfg=`zenity --forms \
		--title="ForemostGUI" \
		--text="Configurer votre récupération de données" \
		--width="800" \
		--add-list="Partitions :" \
		--column-values="Partitions :" \
		--list-values="${parts%?}" \
		--add-entry="Extentions :" \
		--add-entry="Destination :
(default:$PWD/output)" \
		--separator="@"`

#Si on clique sur le bouton Annuler
if [ "$?" -eq 1 ]; then
	#On quitte le script
	exit
fi
#Sinon on continue
addr=`echo "$cfg" | cut -d " " -f1` #Addresse absolue de la partitions sélection
ext=`echo "$cfg" | cut -d "@" -f2` #extentions des fichiers à récupérer
outdir=`echo "$cfg" | cut -d "@" -f3` #dossier de sortie
if [ "$ext" != "" ]; then
	ext="$ext"
else
	ext="all"
fi
if [ "$outdir" != "" ]; then
	outdir="-o $outdir"
fi

#on lance foremost
gksudo -m "L'execution de Foremost nécessite les privilèges administrateur" "foremost -w -q -Q -t '$ext' -i '$addr' $outdir" &
pid=$!
zenity --progress --pulsate --auto-close --text="Récupération en cours..." --title="ForemostGUI"
if [ "$?" -eq 1 ]; then
	gksudo -m "La fermeture de Foremost nécessite les privilèges administrateur" "killall foremost"
else
	zenity --question --title="ForemostGUI" --text="La récupération est terminé.\nVos fichiers sont récupérable ici:\n\"$PWD/output\" avec les privilèges administrateur"
fi
_foremost
}

_foremost