#!/bin/php
<?php
require(__DIR__."/"."Library/autoload.php");
$pathSave="/var/www/html/Repository/ottackuAttack/Web/videos/Musique";
$new_path = "/var/www/html/videos/New";
$extentions=array("mp4", "mkv", "webm");
$undesirables=array("1080" => "", "_" => " ", "(1) " => "", " (Clip Officiel) " => "", " (Clip officiel) " => "", "- YouTube" => "", "- Yo" => "", "- YouT" => "", " (Official Video)" => "", " (Official Music Vide" => "", "- YouTub" => "", " [Official Music Video] " => "", "[" => "", "]" => "", "{" => "", "}" => "", "(" => "", ")" => "", "(17) " => "", "(9) " => "", " (Official) " => "", "- Y" => "", " [OFFICIAL VIDEO] " => "", " (Official Music Video) " => "", " (Official Mus" => "", "- YouTu" => "", "- You" => "", "(OFFICIAL " => "",);
use Library\FilesManager;
use Library\Managers;
use Library\PDOFactory;
$filesManager = new FilesManager;
$managers = new Managers('PDO', PDOFactory::getMysqlConnexion());
$managerVideos = $managers->getManagerOf('Videos');

if($argc == 1){
	$path_array =[$new_path];
}
elseif($argc > 1){
	for($i=0; $i<$argc-1; $i++){
		$path_array[$i] = $filesManager->slasher($argv[$i+1]);
	}
}
foreach($path_array as $path){
	$filesManager->fileFame($path, $extentions, $undesirables, $managerVideos->getAllArtistes());
}